### ISSUE TITLE
Write tests

### ISSUE THREAD

**Issue by allEyezOnCode** [fdardenne/DiscordSINFBot#12]
It would be great to have tests, to avoid bugs when merging 😑

**Comment by fdardenne** [comment]
CI/CD tests and forcing people doing PR to write tests for their functionality?
It seems a bit too demanding to push the community to develop features.

Moreover, I see that the test libraries for Discord.js are not too up-to-date...
On the other hand, what I can do is to test myself the PR before merge them, which I didn't do this time because of the exams.
